-- 002_add_stock_name.sql
-- Adds stock_name column to recommendations for human-readable company names.

ALTER TABLE recommendations
ADD COLUMN stock_name TEXT NOT NULL DEFAULT '';

-- Backfill known tickers with company names
UPDATE recommendations SET stock_name = CASE ticker
    WHEN 'AAPL' THEN 'Apple'
    WHEN 'MSFT' THEN 'Microsoft'
    WHEN 'GOOGL' THEN 'Alphabet'
    WHEN 'GOOG' THEN 'Alphabet'
    WHEN 'AMZN' THEN 'Amazon'
    WHEN 'NVDA' THEN 'NVIDIA'
    WHEN 'META' THEN 'Meta Platforms'
    WHEN 'TSLA' THEN 'Tesla'
    WHEN 'BRK-B' THEN 'Berkshire Hathaway'
    WHEN 'JPM' THEN 'JPMorgan Chase'
    WHEN 'V' THEN 'Visa'
    WHEN 'JNJ' THEN 'Johnson & Johnson'
    WHEN 'WMT' THEN 'Walmart'
    WHEN 'MA' THEN 'Mastercard'
    WHEN 'PG' THEN 'Procter & Gamble'
    WHEN 'UNH' THEN 'UnitedHealth'
    WHEN 'HD' THEN 'Home Depot'
    WHEN 'DIS' THEN 'Walt Disney'
    WHEN 'BAC' THEN 'Bank of America'
    WHEN 'NFLX' THEN 'Netflix'
    WHEN 'CRM' THEN 'Salesforce'
    WHEN 'AMD' THEN 'AMD'
    WHEN 'INTC' THEN 'Intel'
    WHEN 'ADBE' THEN 'Adobe'
    WHEN 'PYPL' THEN 'PayPal'
    WHEN 'COIN' THEN 'Coinbase'
    WHEN 'SQ' THEN 'Block'
    WHEN 'SHOP' THEN 'Shopify'
    WHEN 'UBER' THEN 'Uber'
    WHEN 'ABNB' THEN 'Airbnb'
    WHEN 'SNAP' THEN 'Snap'
    WHEN 'PLTR' THEN 'Palantir'
    WHEN 'RIVN' THEN 'Rivian'
    WHEN 'LCID' THEN 'Lucid'
    WHEN 'NIO' THEN 'NIO'
    WHEN 'SOFI' THEN 'SoFi'
    WHEN 'NET' THEN 'Cloudflare'
    WHEN 'SNOW' THEN 'Snowflake'
    WHEN 'DDOG' THEN 'Datadog'
    WHEN 'ZS' THEN 'Zscaler'
    WHEN 'CRWD' THEN 'CrowdStrike'
    WHEN 'MU' THEN 'Micron'
    WHEN 'AVGO' THEN 'Broadcom'
    WHEN 'QCOM' THEN 'Qualcomm'
    WHEN 'TXN' THEN 'Texas Instruments'
    WHEN 'COST' THEN 'Costco'
    WHEN 'KO' THEN 'Coca-Cola'
    WHEN 'PEP' THEN 'PepsiCo'
    WHEN 'MCD' THEN 'McDonald''s'
    WHEN 'NKE' THEN 'Nike'
    WHEN 'SBUX' THEN 'Starbucks'
    WHEN 'BA' THEN 'Boeing'
    WHEN 'GS' THEN 'Goldman Sachs'
    WHEN 'MS' THEN 'Morgan Stanley'
    WHEN 'C' THEN 'Citigroup'
    WHEN 'WFC' THEN 'Wells Fargo'
    WHEN 'T' THEN 'AT&T'
    WHEN 'VZ' THEN 'Verizon'
    WHEN 'CMCSA' THEN 'Comcast'
    WHEN 'PFE' THEN 'Pfizer'
    WHEN 'MRNA' THEN 'Moderna'
    WHEN 'LLY' THEN 'Eli Lilly'
    WHEN 'ABBV' THEN 'AbbVie'
    WHEN 'BMY' THEN 'Bristol-Myers Squibb'
    WHEN 'XOM' THEN 'ExxonMobil'
    WHEN 'CVX' THEN 'Chevron'
    WHEN 'COP' THEN 'ConocoPhillips'
    WHEN 'F' THEN 'Ford'
    WHEN 'GM' THEN 'General Motors'
    WHEN 'CAT' THEN 'Caterpillar'
    WHEN 'DE' THEN 'Deere'
    WHEN 'UPS' THEN 'UPS'
    WHEN 'FDX' THEN 'FedEx'
    WHEN 'LMT' THEN 'Lockheed Martin'
    WHEN 'RTX' THEN 'RTX'
    WHEN 'GE' THEN 'GE Aerospace'
    WHEN 'HON' THEN 'Honeywell'
    WHEN 'MMM' THEN 'Minnesota Mining'
    WHEN 'SPCE' THEN 'Virgin Galactic'
    WHEN 'ARM' THEN 'Arm Holdings'
    WHEN 'SMCI' THEN 'Super Micro'
    WHEN 'MSTR' THEN 'MicroStrategy'
    WHEN 'DELL' THEN 'Dell'
    WHEN 'ORCL' THEN 'Oracle'
    WHEN 'IBM' THEN 'IBM'
    WHEN 'NOW' THEN 'ServiceNow'
    WHEN 'PANW' THEN 'Palo Alto Networks'
    WHEN 'FTNT' THEN 'Fortinet'
    ELSE ''
END
WHERE stock_name = '';
