"""Ticker → company name lookup table.

Pure data — no AI, no external calls. Used as a fallback when the LLM
omits the stock_name field during extraction.

To add new tickers, just append to the TICKER_NAMES dict below.
"""

TICKER_NAMES: dict[str, str] = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "GOOGL": "Alphabet",
    "GOOG": "Alphabet",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "META": "Meta Platforms",
    "TSLA": "Tesla",
    "BRK-B": "Berkshire Hathaway",
    "BRK-A": "Berkshire Hathaway",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart",
    "MA": "Mastercard",
    "PG": "Procter & Gamble",
    "UNH": "UnitedHealth",
    "HD": "Home Depot",
    "DIS": "Walt Disney",
    "BAC": "Bank of America",
    "NFLX": "Netflix",
    "CRM": "Salesforce",
    "AMD": "AMD",
    "INTC": "Intel",
    "ADBE": "Adobe",
    "PYPL": "PayPal",
    "COIN": "Coinbase",
    "SQ": "Block",
    "SHOP": "Shopify",
    "UBER": "Uber",
    "ABNB": "Airbnb",
    "SNAP": "Snap",
    "PLTR": "Palantir",
    "RIVN": "Rivian",
    "LCID": "Lucid",
    "NIO": "NIO",
    "SOFI": "SoFi",
    "NET": "Cloudflare",
    "SNOW": "Snowflake",
    "DDOG": "Datadog",
    "ZS": "Zscaler",
    "CRWD": "CrowdStrike",
    "MU": "Micron",
    "AVGO": "Broadcom",
    "QCOM": "Qualcomm",
    "TXN": "Texas Instruments",
    "COST": "Costco",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "MCD": "McDonald's",
    "NKE": "Nike",
    "SBUX": "Starbucks",
    "BA": "Boeing",
    "GS": "Goldman Sachs",
    "MS": "Morgan Stanley",
    "C": "Citigroup",
    "WFC": "Wells Fargo",
    "T": "AT&T",
    "VZ": "Verizon",
    "CMCSA": "Comcast",
    "PFE": "Pfizer",
    "MRNA": "Moderna",
    "LLY": "Eli Lilly",
    "ABBV": "AbbVie",
    "BMY": "Bristol-Myers Squibb",
    "XOM": "ExxonMobil",
    "CVX": "Chevron",
    "COP": "ConocoPhillips",
    "F": "Ford",
    "GM": "General Motors",
    "CAT": "Caterpillar",
    "DE": "Deere",
    "UPS": "UPS",
    "FDX": "FedEx",
    "LMT": "Lockheed Martin",
    "RTX": "RTX",
    "GE": "GE Aerospace",
    "HON": "Honeywell",
    "MMM": "3M",
    "SPCE": "Virgin Galactic",
    "SPCX": "SpaceX",
    "ARM": "Arm Holdings",
    "SMCI": "Super Micro",
    "MSTR": "MicroStrategy",
    "DELL": "Dell",
    "ORCL": "Oracle",
    "IBM": "IBM",
    "NOW": "ServiceNow",
    "PANW": "Palo Alto Networks",
    "FTNT": "Fortinet",
    "ANET": "Arista Networks",
    "MRVL": "Marvell",
    "ON": "ON Semiconductor",
    "LRCX": "Lam Research",
    "KLAC": "KLA Corporation",
    "AMAT": "Applied Materials",
    "ASML": "ASML",
    "TSM": "TSMC",
    "SPOT": "Spotify",
    "ROKU": "Roku",
    "TTD": "The Trade Desk",
    "U": "Unity",
    "RBLX": "Roblox",
    "SE": "Sea Limited",
    "MELI": "MercadoLibre",
    "BABA": "Alibaba",
    "JD": "JD.com",
    "PDD": "PDD Holdings",
    "TCEHY": "Tencent",
    "BIDU": "Baidu",
    "WBD": "Warner Bros Discovery",
    "PARA": "Paramount",
    "CHWY": "Chewy",
    "ETSY": "Etsy",
    "W": "Wayfair",
    "ZM": "Zoom",
    "DOCU": "DocuSign",
    "OKTA": "Okta",
    "MDB": "MongoDB",
    "ESTC": "Elastic",
    "PATH": "UiPath",
    "AI": "C3.ai",
    "UPST": "Upstart",
    "AFRM": "Affirm",
    "HOOD": "Robinhood",
    "IONQ": "IonQ",
    "RGTI": "Rigetti",
    "QUBT": "Quantum Computing",
    "CELH": "Celsius",
    "ENPH": "Enphase",
    "SEDG": "SolarEdge",
    "FSLR": "First Solar",
    "RUN": "Sunrun",
    "PLUG": "Plug Power",
    "BE": "Bloom Energy",
    "DKNG": "DraftKings",
    "PENN": "Penn Entertainment",
    "MGM": "MGM Resorts",
    "LVS": "Las Vegas Sands",
    "WYNN": "Wynn Resorts",
    "MAR": "Marriott",
    "HLT": "Hilton",
    "DAL": "Delta Air Lines",
    "UAL": "United Airlines",
    "AAL": "American Airlines",
    "LUV": "Southwest Airlines",
    "CCL": "Carnival",
    "RCL": "Royal Caribbean",
    "LYFT": "Lyft",
    "DASH": "DoorDash",
    "GRAB": "Grab",
    "CPNG": "Coupang",
    "BILI": "Bilibili",
    "FUTU": "Futu Holdings",
    "OPEN": "Opendoor",
    "Z": "Zillow",
    "RDFN": "Redfin",
    "CVNA": "Carvana",
    "GME": "GameStop",
    "AMC": "AMC Entertainment",
    "BBBY": "Bed Bath & Beyond",
    "APE": "AMC Preferred",
    "TLRY": "Tilray",
    "CGC": "Canopy Growth",
    "ACB": "Aurora Cannabis",
    "BYND": "Beyond Meat",
    "LMND": "Lemonade",
    "ROOT": "Root",
    "WISH": "ContextLogic",
    "CLOV": "Clover Health",
    "DNA": "Ginkgo Bioworks",
    "JOBY": "Joby Aviation",
    "ACHR": "Archer Aviation",
    "LILM": "Lilium",
    "EVTL": "Vertical Aerospace",
    "SPWR": "SunPower",
    "XPEV": "XPeng",
    "LI": "Li Auto",
    "PSNY": "Polestar",
    "FSR": "Fisker",
    "VLD": "Velo3D",
    "LAZR": "Luminar",
    "LIDR": "AEye",
    "VLDR": "Velodyne",
    "APPS": "Digital Turbine",
    "BROS": "Dutch Bros",
    "TOST": "Toast",
    "DUOL": "Duolingo",
    "CFLT": "Confluent",
    "HCP": "HashiCorp",
    "S": "SentinelOne",
    "MNDY": "Monday.com",
    "GLBE": "Global-e Online",
    "BILL": "Bill.com",
    "HUBS": "HubSpot",
    "VEEV": "Veeva Systems",
    "TEAM": "Atlassian",
    "WDAY": "Workday",
    "ZI": "ZoomInfo",
    "TWLO": "Twilio",
    "PINS": "Pinterest",
    "MTCH": "Match Group",
    "BMBL": "Bumble",
    "IS": "ironSource",
    "APP": "AppLovin",
    "CRSP": "CRISPR Therapeutics",
    "EDIT": "Editas Medicine",
    "NTLA": "Intellia Therapeutics",
    "BEAM": "Beam Therapeutics",
    "VERV": "Verve Therapeutics",
    "EXAI": "Exscientia",
    "RXRX": "Recursion",
    "SDGR": "Schrödinger",
    "AMGN": "Amgen",
    "GILD": "Gilead Sciences",
    "REGN": "Regeneron",
    "VRTX": "Vertex",
    "BIIB": "Biogen",
    "ISRG": "Intuitive Surgical",
    "DXCM": "DexCom",
    "PODD": "Insulet",
    "AXON": "Axon Enterprise",
    "SNPS": "Synopsys",
    "CDNS": "Cadence Design",
    "ANSS": "ANSYS",
    "ADSK": "Autodesk",
    "INTU": "Intuit",
    "PAYX": "Paychex",
    "ADP": "ADP",
    "FIS": "FIS",
    "FISV": "Fiserv",
    "GPN": "Global Payments",
    "SYK": "Stryker",
    "MDT": "Medtronic",
    "ABT": "Abbott",
    "TMO": "Thermo Fisher",
    "DHR": "Danaher",
    "BDX": "Becton Dickinson",
    "EW": "Edwards Lifesciences",
    "A": "Agilent",
    "ILMN": "Illumina",
    "NDAQ": "Nasdaq",
    "ICE": "Intercontinental Exchange",
    "CME": "CME Group",
    "SCHW": "Charles Schwab",
    "BLK": "BlackRock",
    "SPGI": "S&P Global",
    "MCO": "Moody's",
    "MSCI": "MSCI",
    "TFC": "Truist",
    "USB": "U.S. Bancorp",
    "PNC": "PNC Financial",
    "AXP": "American Express",
    "COF": "Capital One",
    "DFS": "Discover Financial",
    "ALLY": "Ally Financial",
    "MARA": "Marathon Digital",
    "RIOT": "Riot Platforms",
    "CLSK": "CleanSpark",
    "HUT": "Hut 8",
    "BITF": "Bitfarms",
    "CIFR": "Cipher Mining",
    "IREN": "Iris Energy",
    "WULF": "TeraWulf",
    # Tickers from actual DB data (backfilled 2026-06-17)
    "AEP": "American Electric Power",
    "CEG": "Constellation Energy",
    "CLS": "Celestica",
    "CRDO": "CREDO Technology",
    "DLR": "Digital Realty",
    "NESR": "National Energy Services",
    "NLR": "VanEck Uranium+Nuclear ETF",
    "NU": "Nu Holdings",
    "RRR": "Red Rock Resorts",
    "TMUS": "T-Mobile",
    "VRT": "Vertiv",
}


def lookup_stock_name(ticker: str) -> str:
    """Return company name for a ticker, or empty string if unknown."""
    return TICKER_NAMES.get(ticker.upper(), "")
